name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '**.yml'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: phpstan
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_AUTH }}

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: Linux-PHPStan-PHP82-L10-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: Linux-PHPStan-PHP82-L10-composer-

      - name: Add token
        run: |
          composer config github-oauth.github.com ${{ secrets.COMPOSER_AUTH }}
          
      - name: Allow CodeZero
        run: |
          composer config --no-plugins allow-plugins.codezero/composer-preload-files true

      - name: Install dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }' # [tl! **]
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer require "laravel/framework:10.*"  --no-interaction --no-update

      - name: Update dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }' # [tl! **]
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --prefer-stable --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
